In [9]:
import pandas as pd

In [10]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [11]:
data = {
"name": ["Alice", "Bob", "Charlie"],
"age": [25, 30, 35],
"city": ["Delhi", "Mumbai", "Bangalore"]
}
df = pd.DataFrame(data)
print(df)

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [12]:
df.index
df.columns

Index(['name', 'age', 'city'], dtype='str')

In [13]:
import pandas as pd
data = [
["Alice", 25],
["Bob", 30],
["Charlie", 35]
]
df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [14]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])

In [15]:
df = pd.read_excel("")

FileNotFoundError: [Errno 2] No such file or directory: ''

In [ ]:
df = pd.read_json("data.json")

FileNotFoundError: File data.json does not exist

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect("mydb.sqlite")
df = pd.read_sql("SELECT * FROM users", conn)

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df = pd.read_csv(url)

In [ ]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [16]:
df.head()

   A  B
0  1  2
1  3  4

In [17]:
df.tail()

   A  B
0  1  2
1  3  4

In [18]:
df.head() # First 5 rows
df.tail() # Last 5 rows
df.info() # Column info: types, non-nulls
df.describe() # Stats for numeric columns
df.columns # List of column names
df.shape # (rows, columns)

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      int64
 1   B       2 non-null      int64
dtypes: int64(2)
memory usage: 164.0 bytes

(2, 2)